name: Deploy to Heroku

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build_icolors:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        cd ./huu1995vn/apimymystore
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com/v2
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
